name: First_Workflow
on: [workflow_dispatch,push]

jobs:
   build:
      runs-on: macos-latest
      steps:
         - name: Get code
           uses: actions/checkout@v7
         
         - name: Select xcode
           run: sudo xcode-select -s /Applications/Xcode.app

         - name: Build
           run: |
            xcodebuild build \
            -workspace "Pocket Contacts Pro.xcworkspace" \
            -scheme "Pocket Contacts Pro" \
            -sdk iphonesimulator \
            CODE_SIGNING_ALLOWED=NO      
                
                
               
